- UserEntity & mapping implementation
Martell805/JD-8-team1-diploma pull request #15
Opened 2023-03-07 16:28 UTC by skat2006

UserEntity & mapping implementation (UserMapper, UserRepository, UserController, UserServiceImpl)

2023-03-07 17:09 UTC, Martell805 requested changes

2023-03-07 17:09 UTC, Martell805 commented on src/main/java/ru/skypro/homework/controller/AuthController.java
> +    public AuthController(AuthService authService) {
Зачем писать конструктор? По-моему лучше просто аннотацию оставить

2023-03-07 17:09 UTC, Martell805 commented on src/main/java/ru/skypro/homework/dto/LoginReq.java
> +    public String getPassword() {
Тут уже стоит аннотация @Data - она добавляет геттеры на все поля

2023-03-07 17:09 UTC, Martell805 commented on src/main/java/ru/skypro/homework/dto/RegisterReq.java
> +    public String getUsername() {
Тоже уже есть @Data

2023-03-07 17:09 UTC, Martell805 commented on src/main/java/ru/skypro/homework/dto/User.java
> +@ToString
@Data включает в себя @ToString

2023-03-07 17:09 UTC, Martell805 commented on src/main/java/ru/skypro/homework/dto/User.java
> +    public Integer getId() {
Тут аналогично предыдущим

2023-03-07 17:09 UTC, Martell805 commented on src/main/java/ru/skypro/homework/entity/UserEntity.java
>  public class UserEntity {
Тоже лучше просто поставить @Getter и @Setter, или всё заменить на @Data

2023-03-07 17:09 UTC, Martell805 commented on src/main/java/ru/skypro/homework/service/impl/UserServiceImpl.java
>  public class UserServiceImpl {
Опять же можно вместо конструктора @RequiredArgsConstructor

2023-03-07 17:11 UTC, Martell805 commented
В целом - вот руководство по Lombok, он делает код сильно чище
https://habr.com/ru/company/piter/blog/676394/

2023-03-09 14:43 UTC, MaraOD555 approved these changes

2023-03-09 14:43 UTC, MaraOD555 commented
Думаю. что еще в Юзере надо пудет добавить связку на объявления

2023-03-09 15:04 UTC, skat2006 commented on src/main/java/ru/skypro/homework/dto/LoginReq.java
> +    public String getPassword() {
Не знаю почему, но у меня не работает mapstruct без добавления физических геттеров

2023-03-09 16:24 UTC, AnikeevIgor approved these changes

2023-03-09 17:12 UTC, merged