Feature ads controller
Martell805/JD-8-team1-diploma pull request #6
Opened 2023-03-02 19:36 UTC by Martell805

Вроде AdsController не менялся, так что вот

2023-03-02 19:38 UTC, Martell805 commented
Странно, что так много коммитов прошло. Я вроде rebase делал

2023-03-02 19:40 UTC, skat2006 commented
Вот и у меня так же было :)

2023-03-02 19:58 UTC, skat2006 reviewed
...новый openapi

2023-03-02 19:58 UTC, skat2006 commented on src/main/java/ru/skypro/homework/controller/AdsController.java
> +
По новой openapi надо добавить 
@PatchMapping("/{adId}/comments/{commentId}")
Обрати внимание, что все comment изменились на comments, выше тоже надо поменять будет.

2023-03-02 19:58 UTC, skat2006 commented on src/main/java/ru/skypro/homework/controller/AdsController.java
> +}
по новому openapi надо еще добавить что-то типа:
    @PatchMapping(consumes = MediaType.MULTIPART_FORM_DATA_VALUE, path = "/{id}/image")
    public String updateAdsImage(@PathVariable Long id,
                                 @RequestPart("image") MultipartFile multipartFile) {
        return ResponseEntity.ok().build();
    }

2023-03-03 16:08 UTC, MaraOD555 commented on src/main/java/ru/skypro/homework/controller/AdsController.java
> +    public ResponseEntity<AdsComment> addAdsComment(@PathVariable Integer id,
ResponseEntity<AdsComment> addAdsComment, у нас там сейчас в dto comments, думаю надо поправить

2023-03-03 16:08 UTC, MaraOD555 commented on src/main/java/ru/skypro/homework/controller/AdsController.java
> +    public ResponseEntity<AdsComment> deleteAdsComment(@PathVariable Integer id,
и здесь тоже AdsComment на Comment

2023-03-03 16:08 UTC, MaraOD555 commented on src/main/java/ru/skypro/homework/controller/AdsController.java
> +    public ResponseEntity<AdsComment> deleteAdsComment(@PathVariable Integer id,
Ой там тебе Андрей проэто уже писал... не увидела

2023-03-03 17:14 UTC, skat2006 requested changes

2023-03-03 17:14 UTC, skat2006 commented on src/main/java/ru/skypro/homework/controller/AdsController.java
>      @GetMapping("/{id}/comment")
Должно быть /{id}/comments
's' на конце надо добавить во всех comment

2023-03-03 17:14 UTC, skat2006 commented on src/main/java/ru/skypro/homework/controller/AdsController.java
>      @PostMapping("/{id}/comment")
/{id}/comments

2023-03-03 17:14 UTC, skat2006 commented on src/main/java/ru/skypro/homework/controller/AdsController.java
>      @DeleteMapping("/{id}/comment/{commentId}")
/{id}/comments/{commentId}

2023-03-03 17:14 UTC, skat2006 commented on src/main/java/ru/skypro/homework/controller/AdsController.java
>      @GetMapping("/{id}/comment/{commentId}")
/{id}/comments/{commentId}

2023-03-03 17:14 UTC, skat2006 commented on src/main/java/ru/skypro/homework/controller/AdsController.java
>      @PatchMapping("/{id}/comment/{commentId}")
/{id}/comments/{commentId}

2023-03-03 17:23 UTC, MaraOD555 approved these changes

2023-03-03 17:24 UTC, AnikeevIgor approved these changes

2023-03-03 17:42 UTC, skat2006 approved these changes

2023-03-03 17:44 UTC, merged